import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function loadDotEnv() {
  const envPath = resolve(root, ".env");
  if (!existsSync(envPath)) return;

  for (const line of readFileSync(envPath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;

    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;

    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
}

function requireEnv(name) {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

function optionalEnv(name, fallback = "") {
  return process.env[name] || fallback;
}

loadDotEnv();

const output = `// Auto-generated by scripts/generate-config.mjs — do not edit manually.
// Set values in .env (local) or Cloudflare Pages environment variables (production).

export const firebaseConfig = {
  apiKey: ${JSON.stringify(requireEnv("FIREBASE_API_KEY"))},
  authDomain: ${JSON.stringify(requireEnv("FIREBASE_AUTH_DOMAIN"))},
  projectId: ${JSON.stringify(requireEnv("FIREBASE_PROJECT_ID"))},
  storageBucket: ${JSON.stringify(requireEnv("FIREBASE_STORAGE_BUCKET"))},
  messagingSenderId: ${JSON.stringify(requireEnv("FIREBASE_MESSAGING_SENDER_ID"))},
  appId: ${JSON.stringify(requireEnv("FIREBASE_APP_ID"))},
  measurementId: ${JSON.stringify(optionalEnv("FIREBASE_MEASUREMENT_ID"))},
};

export const verifyApiBaseUrl = ${JSON.stringify(requireEnv("VERIFY_API_BASE_URL"))};
`;

writeFileSync(resolve(root, "assets/js/config.js"), output);
console.log("Generated assets/js/config.js");
